export const categories = [
  { en: 'All', ar: 'الكل' },
  { en: 'Pizza', ar: 'بيتزا' },
  { en: 'Burger', ar: 'برجر' },
  { en: 'Sushi', ar: 'سوشي' },
  { en: 'Desserts', ar: 'حلويات' },
  { en: 'Drinks', ar: 'مشروبات' },
  { en: 'Pasta', ar: 'باستا' }
];

export const menuItems = [
  {
    id: 1,
    name: 'Margherita Pizza',
    nameAr: 'بيتزا مارغريتا',
    description: 'Classic pizza with tomatoes and mozzarella cheese, finished with fresh basil.',
    descriptionAr: 'بيتزا كلاسيكية مع الطماطم وجبن الموزاريلا، مزينة بالريحان الطازج.',
    price: 12.99,
    category: 'Pizza',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    badge: { en: 'Popular', ar: 'شائع' },
  },
  {
    id: 2,
    name: 'Truffle Burger',
    nameAr: 'ترفل برجر',
    description: 'Wagyu beef patty, truffle mayo, caramelized onions, and gruyere cheese.',
    descriptionAr: 'شريحة لحم واغيو، مايونيز الكمأة، بصل مكرمل، وجبن الغرويير.',
    price: 18.50,
    category: 'Burger',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    badge: { en: 'Chef\'s Special', ar: 'اختيار الشيف' },
  },
  {
    id: 3,
    name: 'Spicy Tuna Roll',
    nameAr: 'رول التونة الحار',
    description: 'Fresh tuna with spicy mayo, cucumber, and topped with sesame seeds.',
    descriptionAr: 'تونة طازجة مع المايونيز الحار والخيار ومغطاة ببذور السمسم.',
    price: 14.00,
    category: 'Sushi',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 4,
    name: 'Chocolate Lava Cake',
    nameAr: 'كيكة اللافا بالشوكولاتة',
    description: 'Warm chocolate cake with a gooey center, served with vanilla bean ice cream.',
    descriptionAr: 'كيكة شوكولاتة دافئة مع قلب لزج، تقدم مع آيس كريم الفانيليا.',
    price: 8.99,
    category: 'Desserts',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 5,
    name: 'Artisan Lemonade',
    nameAr: 'ليموناضة آرتيزان',
    description: 'Freshly squeezed lemons with a hint of mint and agave.',
    descriptionAr: 'عصير ليمون طازج مع لمسة من النعناع والأغاف.',
    price: 4.50,
    category: 'Drinks',
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 6,
    name: 'Pepperoni Feast',
    nameAr: 'وليمة البيبروني',
    description: 'Loaded with premium pepperoni and extra cheese on a thin crust.',
    descriptionAr: 'محملة بالبيبروني الفاخر والجبن الإضافي على قشرة رقيقة.',
    price: 15.99,
    category: 'Pizza',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 7,
    name: 'Fettuccine Alfredo',
    nameAr: 'فيتوتشيني ألفريدو',
    description: 'Creamy parmesan sauce with grilled chicken and fresh parsley.',
    descriptionAr: 'صلصة بارميزان كريمية مع الدجاج المشوي والبقدونس الطازج.',
    price: 16.50,
    category: 'Pasta',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 8,
    name: 'Dragon Sushi Roll',
    nameAr: 'رول دراجون سوشي',
    description: 'Eel and cucumber inside, topped with avocado and sweet eel sauce.',
    descriptionAr: 'ثعبان البحر والخيار في الداخل، مغطى بالأفوكادو وصلصة ثعبان البحر الحلوة.',
    price: 19.99,
    category: 'Sushi',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1553621042-f6e147245754?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    badge: { en: 'New', ar: 'جديد' }
  },
  {
    id: 9,
    name: 'Iced Matcha Latte',
    nameAr: 'ماتشا لاتيه مثلج',
    description: 'Premium ceremonial grade matcha with oat milk and honey.',
    descriptionAr: 'ماتشا فاخرة مع حليب الشوفان والعسل.',
    price: 6.50,
    category: 'Drinks',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 10,
    name: 'Tiramisu',
    nameAr: 'تيراميسو',
    description: 'Classic Italian dessert with espresso-soaked ladyfingers and mascarpone.',
    descriptionAr: 'حلوى إيطالية كلاسيكية مع أصابع الإسفنج المنقوعة بالإسبريسو والماسكاربوني.',
    price: 9.50,
    category: 'Desserts',
    rating: 4.9,
    image: 'https://modo3.com/thumbs/fit630x300/3921/1384413804/%D8%B7%D8%B1%D9%8A%D9%82%D8%A9_%D8%B9%D9%85%D9%84_%D8%A7%D9%84%D8%AA%D9%8A%D8%B1%D8%A7%D9%85%D9%8A%D8%B3%D9%88.jpg',
    badge: { en: 'Must Try', ar: 'يجب تجربته' }
  }
];
